// Conversion d'un nom de pays (tel que renvoyé par l'API 42) en drapeau emoji.
// La table couvre tous les pays ISO 3166-1 ; la normalisation (minuscules,
// sans accents ni ponctuation) absorbe les variantes d'écriture.

function normalize(s: string): string {
  let out = "";
  for (const ch of s.normalize("NFD").toLowerCase()) {
    const code = ch.codePointAt(0)!;
    // Ignore les marques combinantes (accents décomposés) U+0300–U+036F.
    if (code >= 0x0300 && code <= 0x036f) continue;
    if ((ch >= "a" && ch <= "z") || (ch >= "0" && ch <= "9")) out += ch;
  }
  return out;
}

// Nom anglais (forme la plus courante) → code ISO alpha-2.
const RAW: Record<string, string> = {
  Afghanistan: "AF",
  Albania: "AL",
  Algeria: "DZ",
  Andorra: "AD",
  Angola: "AO",
  Argentina: "AR",
  Armenia: "AM",
  Australia: "AU",
  Austria: "AT",
  Azerbaijan: "AZ",
  Bahamas: "BS",
  Bahrain: "BH",
  Bangladesh: "BD",
  Belarus: "BY",
  Belgium: "BE",
  Benin: "BJ",
  Bolivia: "BO",
  "Bosnia and Herzegovina": "BA",
  Botswana: "BW",
  Brazil: "BR",
  Bulgaria: "BG",
  "Burkina Faso": "BF",
  Cambodia: "KH",
  Cameroon: "CM",
  Canada: "CA",
  Chad: "TD",
  Chile: "CL",
  China: "CN",
  Colombia: "CO",
  "Costa Rica": "CR",
  "Ivory Coast": "CI",
  "Cote d'Ivoire": "CI",
  Croatia: "HR",
  Cuba: "CU",
  Cyprus: "CY",
  "Czech Republic": "CZ",
  Czechia: "CZ",
  "Democratic Republic of the Congo": "CD",
  Denmark: "DK",
  "Dominican Republic": "DO",
  Ecuador: "EC",
  Egypt: "EG",
  "El Salvador": "SV",
  Estonia: "EE",
  Ethiopia: "ET",
  Finland: "FI",
  France: "FR",
  Gabon: "GA",
  Georgia: "GE",
  Germany: "DE",
  Ghana: "GH",
  Greece: "GR",
  Guatemala: "GT",
  Guinea: "GN",
  Honduras: "HN",
  "Hong Kong": "HK",
  Hungary: "HU",
  Iceland: "IS",
  India: "IN",
  Indonesia: "ID",
  Iran: "IR",
  Iraq: "IQ",
  Ireland: "IE",
  Israel: "IL",
  Italy: "IT",
  Jamaica: "JM",
  Japan: "JP",
  Jordan: "JO",
  Kazakhstan: "KZ",
  Kenya: "KE",
  Kosovo: "XK",
  Kuwait: "KW",
  Kyrgyzstan: "KG",
  Laos: "LA",
  Latvia: "LV",
  Lebanon: "LB",
  Liberia: "LR",
  Libya: "LY",
  Liechtenstein: "LI",
  Lithuania: "LT",
  Luxembourg: "LU",
  Madagascar: "MG",
  Malaysia: "MY",
  Maldives: "MV",
  Mali: "ML",
  Malta: "MT",
  Mauritania: "MR",
  Mauritius: "MU",
  Mexico: "MX",
  Moldova: "MD",
  Monaco: "MC",
  Mongolia: "MN",
  Montenegro: "ME",
  Morocco: "MA",
  Mozambique: "MZ",
  Myanmar: "MM",
  Namibia: "NA",
  Nepal: "NP",
  Netherlands: "NL",
  "New Zealand": "NZ",
  Nicaragua: "NI",
  Niger: "NE",
  Nigeria: "NG",
  "North Macedonia": "MK",
  Norway: "NO",
  Oman: "OM",
  Pakistan: "PK",
  Palestine: "PS",
  Panama: "PA",
  Paraguay: "PY",
  Peru: "PE",
  Philippines: "PH",
  Poland: "PL",
  Portugal: "PT",
  Qatar: "QA",
  "Republic of the Congo": "CG",
  Romania: "RO",
  Russia: "RU",
  "Russian Federation": "RU",
  Rwanda: "RW",
  "Saudi Arabia": "SA",
  Senegal: "SN",
  Serbia: "RS",
  Singapore: "SG",
  Slovakia: "SK",
  Slovenia: "SI",
  Somalia: "SO",
  "South Africa": "ZA",
  "South Korea": "KR",
  Korea: "KR",
  "Republic of Korea": "KR",
  Spain: "ES",
  "Sri Lanka": "LK",
  Sudan: "SD",
  Sweden: "SE",
  Switzerland: "CH",
  Syria: "SY",
  Taiwan: "TW",
  Tajikistan: "TJ",
  Tanzania: "TZ",
  Thailand: "TH",
  Togo: "TG",
  "Trinidad and Tobago": "TT",
  Tunisia: "TN",
  Turkey: "TR",
  "Türkiye": "TR",
  Turkmenistan: "TM",
  Uganda: "UG",
  Ukraine: "UA",
  "United Arab Emirates": "AE",
  "United Kingdom": "GB",
  "United States": "US",
  "United States of America": "US",
  Uruguay: "UY",
  Uzbekistan: "UZ",
  Venezuela: "VE",
  Vietnam: "VN",
  Yemen: "YE",
  Zambia: "ZM",
  Zimbabwe: "ZW",
};

// Abréviations + formes officielles ISO (format inversé avec virgule) telles
// que l'API 42 les renvoie réellement. La normalisation gère la virgule/espaces.
const ALIASES: Record<string, string> = {
  usa: "US",
  us: "US",
  uk: "GB",
  uae: "AE",
  drc: "CD",
  "Korea, Republic of": "KR",
  "Korea, Democratic People's Republic of": "KP",
  "Moldova, Republic of": "MD",
  "Palestine, State of": "PS",
  "Tanzania, United Republic of": "TZ",
  "Iran, Islamic Republic of": "IR",
  "Bolivia, Plurinational State of": "BO",
  "Venezuela, Bolivarian Republic of": "VE",
  "Congo, Democratic Republic of the": "CD",
  "Congo, Republic of the": "CG",
  "Taiwan, Province of China": "TW",
  "Syrian Arab Republic": "SY",
  "Viet Nam": "VN",
  "Lao People's Democratic Republic": "LA",
  "Macedonia, the former Yugoslav Republic of": "MK",
  "Hong Kong, SAR China": "HK",
};

const LOOKUP: Record<string, string> = {};
for (const [name, iso] of Object.entries(RAW)) LOOKUP[normalize(name)] = iso;
for (const [name, iso] of Object.entries(ALIASES)) LOOKUP[normalize(name)] = iso;

export function countryFlag(country?: string): string {
  if (!country) return "🌐";
  const iso = LOOKUP[normalize(country)];
  if (!iso) return "🌐";
  return iso
    .toUpperCase()
    .replace(/./g, (ch) => String.fromCodePoint(127397 + ch.charCodeAt(0)));
}
